propietario:
    resource: "@PropietarioBundle/Resources/config/routing.yml"
    prefix:   /propietario

animales:
    resource: "@AnimalesBundle/Resources/config/routing.yml"
    prefix:   /animales

anuncios:
    resource: "@AnunciosBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

s_pruebas_pruebas:
    resource: "@SPruebasPRUEBASBundle/Resources/config/routing.yml"
    prefix:   /

pruebas:
    resource: "@PruebasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group