AnunciosBundle\Entity\Anuncios:
    type: entity
    table: null
    repositoryClass: AnunciosBundle\Repository\AnunciosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: 255
            column: Titulo
        idAnimal:
            type: integer
            unique: true
            column: IdAnimal
        nombrePropietario:
            type: string
            length: 255
            column: NombrePropietario
        email:
            type: string
            length: 255
            unique: true
            column: Email
    lifecycleCallbacks: {  }
