PropietarioBundle\Entity\Propietario:
    type: entity
    table: null
    repositoryClass: PropietarioBundle\Repository\PropietarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
            column: Nombre
        email:
            type: string
            length: 255
            column: Email
        apellido:
            type: string
            length: 255
            column: Apellido
        anuncio:
            type: string
            length: 255
            column: Anuncio
        telefono:
            type: integer
            column: Telefono
        direccion:
            type: string
            length: 255
            column: Direccion
        cP:
            type: string
            length: 255
            column: CP
        animal:
            type: string
            length: 255
            column: Animal
    lifecycleCallbacks: {  }
